# Generated by Django 4.2.6 on 2023-12-27 19:41

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_password_created_password_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="password",
            name="ciphertext",
        ),
        migrations.AddField(
            model_name="password",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=1000)
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to="api.password",
                    ),
                ),
            ],
        ),
    ]
